name       : libmatemixer
version    : 1.14.0
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/libmatemixer-1.14.0.tar.xz : 8293a0b0c125b4749e415fb2e4f80adcf313b769ce02f49521d6ddd323d7c07d
license    : LGPL-2.1
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop.
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libpulse-mainloop-glib)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --disable-static
build      : |
    %make
install    : |
    %make_install
