name       : libmatemixer
version    : 1.18.0
release    : 4
source     :
    - http://pub.mate-desktop.org/releases/1.18/libmatemixer-1.18.0.tar.xz : b99209e310ba614c5b0bd6a97545ba974bc34a74cd29fd50189a5365a9ed7e27
license    : LGPL-2.1
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop.
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libpulse-mainloop-glib)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --disable-static
build      : |
    %make
install    : |
    %make_install
