name       : libmatemixer
version    : 1.20.0
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmatemixer-1.20.0.tar.xz : 65fdfca268b47a4c12cf95c7187d30fd1db0e0afed3fedcd9655d8ab1756ee4a
license    : LGPL-2.1
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop.
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libpulse-mainloop-glib)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --disable-static
build      : |
    %make
install    : |
    %make_install
