name       : libmatemixer
version    : 1.16.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.16/libmatemixer-1.16.0.tar.xz : 83ca5fbfd7d8c3904e5ebfd84c17e0b005682551541463f77f703fa97804cf09
license    : LGPL-2.1
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop.
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libpulse-mainloop-glib)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --disable-static
build      : |
    %make
install    : |
    %make_install
