name       : libmatemixer
version    : 1.26.0
release    : 14
source     :
    - https://github.com/mate-desktop/libmatemixer/releases/download/v1.26.0/libmatemixer-1.26.0.tar.xz : 9a9bcc605b27e9c5c91a28eb7cb79831e6d6fbf6339f5e5c18d524f3ee259ff1
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk-doc)
    - pkgconfig(libpulse)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --enable-gtk-doc \
               --disable-static
build      : |
    %make
install    : |
    %make_install
