name       : libmatemixer
version    : 1.24.1
release    : 13
source     :
    - https://github.com/mate-desktop/libmatemixer/archive/v1.24.1.tar.gz : 5b9c8f8a79a2ec50aa92542950170217865b415ee0f204f16183ebce29aa91ae
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk-doc)
    - pkgconfig(libpulse)
    - mate-common
setup      : |
    %autogen --enable-pulseaudio \
             --enable-alsa \
             --enable-gtk-doc \
             --disable-static
build      : |
    %make
install    : |
    %make_install
