name       : libmatemixer
version    : 1.27.0
release    : 15
source     :
    - https://github.com/mate-desktop/libmatemixer/releases/download/v1.27.0/libmatemixer-1.27.0.tar.xz : 1d4c2db1efbc9a4f4c3d310531c8b124af690a366fa4923d87979f2ca1d3b53e
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk-doc)
    - pkgconfig(libpulse)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --enable-gtk-doc \
               --disable-static
build      : |
    %make
install    : |
    %make_install
