name       : libmatemixer
version    : 1.22.0
release    : 9
source     :
    - https://github.com/mate-desktop/libmatemixer/archive/v1.22.0.tar.gz : feeeab32ccf94a86c5b57dac78a6f3316918d96d5f1fbb7fb2f603b3f7dfae4b
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk-doc)
    - pkgconfig(libpulse)
    - mate-common
setup      : |
    %autogen --enable-pulseaudio \
             --enable-alsa \
             --enable-gtk-doc \
             --disable-static
build      : |
    %make
install    : |
    %make_install
