name       : libmatemixer
version    : 1.20.1
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmatemixer-1.20.1.tar.xz : 239106f666d79abf578eb02eaa63d12724f73330985f5c827d4b5307623de602
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop.
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gobject-2.0)
    - pkgconfig(libpulse-mainloop-glib)
setup      : |
    %configure --enable-pulseaudio \
               --enable-alsa \
               --disable-static
build      : |
    %make
install    : |
    %make_install
