name       : libmatemixer
version    : 1.24.0
release    : 12
source     :
    - https://github.com/mate-desktop/libmatemixer/archive/v1.24.0.tar.gz : a7b405f8299245ad3382f53d4cbca9c74044f9c6b66fe600408e271f34ea5a53
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : libmatemixer is a mixer library for MATE desktop
description: |
    libmatemixer is a mixer library for MATE desktop.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk-doc)
    - pkgconfig(libpulse)
    - mate-common
setup      : |
    %autogen --enable-pulseaudio \
             --enable-alsa \
             --enable-gtk-doc \
             --disable-static
build      : |
    %make
install    : |
    %make_install
